### ISSUE TITLE
Zipfile

### ISSUE THREAD

**Issue by Arwy17** [Sp00p64/DiscordRAT#29]
Hello, 
I cant install requirements cuz I cannot install zipfile in requirements
![image](https://user-images.githubusercontent.com/64810761/115992426-00c9c000-a5ce-11eb-93e0-62bfca70be70.png)

**Comment by Sp00p64** [comment]
That's because zipfile is built-in python so it shouldn't have been included in the requirements file, this has been fixed.

**Comment by Arwy17** [comment]
but I removed zipfile and it's still not working idk mby u can help me on discord?

**Comment by Sp00p64** [comment]
If it's not working please post the error message or describe the problem here.

**Comment by Arwy17** [comment]
idk now its saying that PyInstaller is not recognized command

**Comment by Sp00p64** [comment]
That means that pyinstaller is not installed on your system you can install it doing : `python -m pip install pyinstaller` 
Remember that pyinstaller is optional for this program and you can just execute it by doing : `python DiscordRAT.py`

**Comment by Arwy17** [comment]
it didn't create any room
I executabled it and open and it didn't create nothing

**Comment by Arwy17** [comment]
i turned off antivirus too

**Comment by Arwy17** [comment]
yeah its grabber

**Comment by Laar-u** [comment]
> 
> 
> yeah its grabber

any proof doe?
